# Generated by Django 4.0.3 on 2022-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('prix', models.FloatField()),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('prix', models.FloatField()),
            ],
            options={
                'db_table': 'design',
            },
        ),
        migrations.CreateModel(
            name='Developpement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('prix', models.FloatField()),
            ],
            options={
                'db_table': 'developpement',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('prix', models.FloatField()),
                ('duree', models.IntegerField()),
            ],
            options={
                'db_table': 'visa',
            },
        ),
    ]
