# Generated by Django 4.0.3 on 2022-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_actualite_alter_about_image_alter_application_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
